"""
train_xgboost.py
----------------

Train an XGBoost model for network intrusion detection.

This script trains a Gradient Boosted Decision Tree model
using the ML-ready datasets generated by prepare_ml_dataset.py.
"""

import logging
import os
import time

import joblib
import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    f1_score,
    precision_score,
    recall_score,
)
from xgboost import XGBClassifier

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

INPUT_DIR  = "processed_ml"
MODEL_DIR  = "models"
MODEL_PATH = os.path.join(MODEL_DIR, "xgboost_model.pkl")

XGB_PARAMS = dict(
    objective="multi:softprob",
    n_estimators=300,
    learning_rate=0.05,
    max_depth=8,
    subsample=0.8,
    colsample_bytree=0.8,
    tree_method="hist",
    n_jobs=-1,
    random_state=42,
    verbosity=0,
)

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _load_parquet(name: str) -> pd.DataFrame:
    path = os.path.join(INPUT_DIR, f"{name}.parquet")
    df = pd.read_parquet(path)
    log.info("Loaded %-35s  shape=%s", name + ".parquet", df.shape)
    return df


def _to_series(obj: pd.DataFrame | pd.Series) -> pd.Series:
    """Flatten a single-column DataFrame to a Series."""
    if isinstance(obj, pd.DataFrame):
        return obj.iloc[:, 0]
    return obj


# ---------------------------------------------------------------------------
# Pipeline steps
# ---------------------------------------------------------------------------

def load_datasets() -> tuple[
    pd.DataFrame, pd.DataFrame, pd.DataFrame,
    pd.Series,   pd.Series,   pd.Series,
]:
    log.info("Loading datasets from: %s", INPUT_DIR)

    X_train = _load_parquet("X_train")
    X_val   = _load_parquet("X_val")
    X_test  = _load_parquet("X_test")

    y_train = _to_series(_load_parquet("y_multiclass_train"))
    y_val   = _to_series(_load_parquet("y_multiclass_val"))
    y_test  = _to_series(_load_parquet("y_multiclass_test"))

    log.info(
        "Dataset sizes — train: %d | val: %d | test: %d",
        len(X_train), len(X_val), len(X_test),
    )
    log.info("Number of features : %d", X_train.shape[1])
    return X_train, X_val, X_test, y_train, y_val, y_test


def train_model(
    X_train: pd.DataFrame,
    y_train: pd.Series,
    X_val: pd.DataFrame,
    y_val: pd.Series,
    n_classes: int,
) -> XGBClassifier:
    params = {**XGB_PARAMS, "num_class": n_classes}
    log.info("Training XGBClassifier  params=%s", params)

    clf = XGBClassifier(**params)

    t0 = time.perf_counter()
    clf.fit(
        X_train, y_train,
        eval_set=[(X_val, y_val)],
        verbose=False,
    )
    elapsed = time.perf_counter() - t0

    log.info("Training complete in %.1f seconds.", elapsed)
    return clf


def evaluate(
    clf: XGBClassifier,
    X: pd.DataFrame,
    y_true: pd.Series,
    split_name: str,
) -> None:
    y_pred = clf.predict(X)

    acc  = accuracy_score(y_true, y_pred)
    prec = precision_score(y_true, y_pred, average="macro", zero_division=0)
    rec  = recall_score(y_true, y_pred, average="macro", zero_division=0)
    f1   = f1_score(y_true, y_pred, average="macro", zero_division=0)

    log.info("[%s]  accuracy=%.4f  precision=%.4f  recall=%.4f  F1=%.4f",
             split_name, acc, prec, rec, f1)

    report = classification_report(y_true, y_pred, zero_division=0)
    print(f"\n{'='*60}")
    print(f"  Classification Report — {split_name}")
    print(f"{'='*60}")
    print(report)

    return dict(accuracy=acc, precision=prec, recall=rec, f1=f1)


def save_model(clf: XGBClassifier) -> None:
    os.makedirs(MODEL_DIR, exist_ok=True)
    joblib.dump(clf, MODEL_PATH)
    log.info("Saved model → %s", MODEL_PATH)


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def run_pipeline() -> None:
    """End-to-end XGBoost training and evaluation pipeline."""

    # 1. Load ----------------------------------------------------------------
    X_train, X_val, X_test, y_train, y_val, y_test = load_datasets()

    # 2. Infer number of classes ---------------------------------------------
    n_classes = int(y_train.nunique())
    log.info("Number of classes: %d", n_classes)

    # 3. Train ---------------------------------------------------------------
    clf = train_model(X_train, y_train, X_val, y_val, n_classes)

    # 4. Evaluate on validation set ------------------------------------------
    val_metrics = evaluate(clf, X_val, y_val, "Validation")

    # 5. Evaluate on test set ------------------------------------------------
    test_metrics = evaluate(clf, X_test, y_test, "Test")

    # 6. Save model ----------------------------------------------------------
    save_model(clf)

    # 7. Summary -------------------------------------------------------------
    print("\n" + "=" * 60)
    print("  XGBoost — Final Summary")
    print("=" * 60)
    for name, m in [("Validation", val_metrics), ("Test", test_metrics)]:
        print(f"  [{name}]")
        print(f"    Accuracy          : {m['accuracy']:.4f}")
        print(f"    Precision (macro) : {m['precision']:.4f}")
        print(f"    Recall    (macro) : {m['recall']:.4f}")
        print(f"    F1-score  (macro) : {m['f1']:.4f}")
    print("=" * 60)
    print(f"  Model saved : {os.path.abspath(MODEL_PATH)}")
    print("=" * 60 + "\n")


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    run_pipeline()
